### ISSUE TITLE
Quick bring notes to front / send back

### ISSUE THREAD

**Issue by wokawoka** [itsmejoeeey/eversticky#1]
First of all, thank you for this great project! I'm testing it at the moment and it's already extremely useful like it is at the moment!

I don't know if you accept feature requests/suggestions as issues, but I was thinking that what I'd need the most at this point is a way to quickly bring the notes to the foreground and send them back in the background. Doing it via a single click on the app icon would be great, being able to use a user's definable shortcut to do so would be even better.
What do you think?
Thank you again for the great work you are doing

**Comment by itsmejoeeey** [comment]
Bringing notes to the foreground when activating/clicking on the tray icon is a good suggestion.

This is included in [new release v0.95.2](https://github.com/itsmejoeeey/eversticky/releases/tag/v0.95.2).
