### ISSUE TITLE
How to import notes from the cloud to the system

### ISSUE THREAD

**Issue by vincent1890** [itsmejoeeey/eversticky#13]
Good morning,

Your application is just fabulous but I don’t understand how to import notes from the cloud on my ubuntu 22.04.

I can create some and this one is exported on evernote but not the reverse is this normal?

Thank you for your response

And thank you for this application which is currently the only linux-based one to communicate with the cloud and therefore all the machines potentially (when I find out how to import my notes on my second machine).

**Comment by itsmejoeeey** [comment]
Note syncing occurs both ways.

Notes are shown only from the notebook `Sticky Notes` (created on application first run if it doesn't already exist). Ensure the notes you are creating from other clients are created in this notebook.

**Comment by itsmejoeeey** [comment]
I clarified the expected behavior in my last comment - without further details I don't believe there is a bug here.

Closing this issue as it has been inactive for 14 days.
