### ISSUE TITLE
Sync failure

### ISSUE THREAD

**Issue by tim-oh** [itsmejoeeey/eversticky#19]
EverSticky doesn't display Evernote notes

I have a free Evernote account on which I collect simple to do notes and task lists for various projects, and want to use Eversticky to sync notes across my dual-boot set-up. The app launches, as evident by the icon in the Ubuntu top bar, but it doesn't display the notes that are available online (or in the Windows desktop app).

**Reproduction**
These were my steps, can't say if this reproduces:
1. Create Evernote account.
2. Download Evernote Windows desktop app.
3. Create notes (they're visible in the Windows app and online).
4. Download, install and launch Eversticky.
5. Log into the Evernote account.
6. Force sync (nothing happens).
7. Create a test note: gets uploaded to Evernote, but no download happens.

**Expected behaviour** 
As above, but from
6. Force sync downloads existing notes.
7. 'Bring notes to foreground' shows existing notes.

**Desktop:**
 - Ubuntu 22.04.3 LTS with Eversticky
 - Windows 11 with Evernote app
 - Hardware: XPS 15 9530

**Comment by itsmejoeeey** [comment]
Please upload the console log.

The application only displays notes in the `Sticky Notes` notebook, is that where your notes are?

**Comment by tim-oh** [comment]
Thanks for the pointer, I was new to Evernote and didn't realise that there's a separate sticky notebook
