### ISSUE TITLE
Crash on network/sync issue

### ISSUE THREAD

**Issue by wokawoka** [itsmejoeeey/eversticky#2]
evernote servers have been not responding for a while (my experience is that it happens from time to time) and I noticed that I couldn´t bring back the eversticky's notes. It was like they were not there. A bit later eversticky crashed. 
Would it by chance possible to have the local copies of the notes always available so that the sticky notes are be accessible in any network condition?
Thank you!

**Comment by itsmejoeeey** [comment]
The application already does local caching as you describe. 

I've experienced this bug myself. In some circumstances the application must be failing to catch the network/server errors.

Could you please post the terminal output of the application after a crash? This should help give a bit more clarity around the exact causes of the crash.

**Comment by wokawoka** [comment]
sure, from now on I'll try to launch the application from terminal and I'll attach the output as soon as it will happen again.
Thank you

**Comment by itsmejoeeey** [comment]
I managed to reproduce the issue and I've fixed it in [new release v0.95.1](https://github.com/itsmejoeeey/eversticky/releases/tag/v0.95.1). Closing.
