### ISSUE TITLE
no login

### ISSUE THREAD

**Issue by m4lin** [itsmejoeeey/eversticky#20]
**Describe the bug**
app installed (compiling from source), run, trying to login everything stop with error

**To Reproduce**
1. click on login
2. error

**Expected behavior**
Asking me login details i guess

**Screenshots**
![everstickyError](https://github.com/user-attachments/assets/4c376f62-b84b-4bda-aa79-7c9907e47655)

**Desktop (please complete the following information):**
 - OS: Void Linux
 - Version N.A. rolling, 

**Additional context**
Maybe i am missing how to pass login details, but i cannot find much information

**Comment by m4lin** [comment]
After the first make i realized the Important note on how to pass login details/keys, i edited the .pro file and run make again, but had the same results, am i miss something?

thanks

**Comment by itsmejoeeey** [comment]
Sorry for the delay in replying.

You will get this error if after cloning (and before building) you have not updated the file at `src/eversticky.pro` with the correct details (replacing the `XXX..XX` characters). You will need to get an Evernote Developer API Key from Evernote. I've tried to document these fields in the file itself:

```
    ## API_DOMAIN
    # Can be either 'www.evernote.com' or 'sandbox.evernote.com' for testing
    # --> If error 'Host requires authentication' you must go to 'https://dev.evernote.com/support/'
    #       to request activation of your API key on our production service.
    API_HOST=\\\"XXXXXXXXXXXXXXXX\\\" \
    #
    ## API_KEY
    # Typically The username of the user than owns the API key
    API_KEY=\\\"XXXXXXXXXXXXXXXX\\\" \
    #
    ## API_SECRET
    # The 16-digit API key
    API_SECRET=\\\"XXXXXXXXXXXXXXXX\\\"
```

After updating this file, you can run the build commands outlined in the `README` file.
