### ISSUE TITLE
Crash when I try to create a new note

### ISSUE THREAD

**Issue by ivanottantuno** [itsmejoeeey/eversticky#3]
It crash when I try to create a new note. So I launch it from the terminal and I've got this error when it crash.

`eversticky`
[2021-11-17T12:45:34] Icon theme "ubuntu-mono-dark" not found.
[2021-11-17T12:45:34] Icon theme "Mint-X" not found.
[2021-11-17T12:45:34] Icon theme "elementary" not found.
[2021-11-17T12:45:34] "No carrier"
[2021-11-17T12:45:35] Synchronising notes from Evernote.
[2021-11-17T12:45:35] Found 0 notes.
fish: 'eversticky' terminated by signal SIGSEGV (Address boundary error)

`dpkg --status eversticky`                                                                                                                 
Package: eversticky
Status: install ok installed
Maintainer: Joey Miller <eversticky@joeeey.com>
Architecture: amd64
Version: 0.95.0
Depends: libc6 (>= 2.14), libgcc-s1 (>= 3.0), libqt5core5a (>= 5.12.2), libqt5gui5 (>= 5.3.0) | libqt5gui5-gles (>= 5.3.0), libqt5network5 (>= 5.0.2), libqt5sql5 (>= 5.0.2), libqt5webchannel5 (>= 5.6.1), libqt5webenginewidgets5 (>= 5.7.1), libqt5widgets5 (>= 5.9.0~beta), libqt5x11extras5 (>= 5.6.0), libqt5xml5 (>= 5.0.2), libstdc++6 (>= 5.2), libx11-6
Description: A sticky note client that sync to Evernote.
Homepage: https://eversticky.joeeey.com

`dpkg --status plasma-workspace-wayland`                                                                                               
Package: plasma-workspace-wayland
Status: install ok installed
Priority: optional
Section: kde
Installed-Size: 264
Maintainer: Debian Qt/KDE Maintainers <debian-qt-kde@lists.debian.org>
Architecture: amd64
Source: plasma-workspace
Version: 4:5.23.3-1\~np1
Depends: kwayland-integration (>= 5.23\~), kwin-wayland (>= 4:5.20\~), plasma-workspace (= 4:5.23.3-1\~np1), qtwayland5, libc6 (>= 2.4), libkf5configcore5 (>= 5.82.0\~), libkf5coreaddons5 (>= 5.86\~), libkworkspace5-5 (= 4:5.23.3-1\~np1), libqt5core5a (>= 5.15.1), libqt5dbus5 (>= 5.15.0\~), libstdc++6 (>= 5)
Description: Plasma Workspace for KF5 - Wayland integration
 Plasma Workspace for KF5. Workspaces provide
 support for KDE Plasma Widgets, integrated search,
 hardware management and a high degree of customizability.
 .
 This package contains the Wayland session.
Homepage: https://invent.kde.org/plasma/plasma-workspace

`neofetch --backend off`                                                                                                                   
---------------- 
OS: Debian GNU/Linux 11 (bullseye) x86_64 
Host: Aspire 5749Z V1.08 
Kernel: 5.14.0-18.1-liquorix-amd64 
Uptime: 1 day, 2 hours, 24 mins 
Packages: 5788 (dpkg) 
Shell: fish 3.1.2 
Resolution: 1366x768 
DE: Plasma 5.23.3 
WM: kwin 
Theme: Breeze Light [Plasma], Sweet-Dark [GTK2/3] 
Icons: Sweet-Rainbow [Plasma], Sweet-Rainbow [GTK2/3] 
Terminal: yakuake 
CPU: Intel Pentium B960 (2) @ 2.200GHz 
GPU: Intel 2nd Generation Core Processor Family 
Memory: 3597MiB / 7812MiB

**Comment by itsmejoeeey** [comment]
I haven't encountered this issue myself during testing (although I haven't done any testing on Wayland, which EverSticky doesn't officially support at the moment).

Do you have any way of reliably reproducing this crash, or is this a one-off? 

[New release v0.95.1](https://github.com/itsmejoeeey/eversticky/releases/tag/v0.95.1) addressed a number of bugs. Try that and get back to me if you can still see the issue.

**Comment by ivanottantuno** [comment]
launched with
QT_QPA_PLATFORM=xcb eversticky
it doesn't crash, both the binary in the .deb package and the one compiled from source.
About the compiled one in this attachment
[make.log](https://github.com/itsmejoeeey/eversticky/files/7703167/make.log)
there are some warnings during the compile process.
