### ISSUE TITLE
Loses evernote login authorisation when started immediately after bootup/ in specific network conditions

### ISSUE THREAD

**Issue by wokawoka** [itsmejoeeey/eversticky#4]
Hello again, I added eversticky to my startup programs queue and today, after I rebooted eversticky regularly started but popped up an error dialog complaining that it was not able to reach evernote. After having clicked ok I had to relogin to reauthorise it to login to evernote (that means requesting once again the evernote sms otp).
I assume that eversticky was not able to connect to evernote servers because the system was starting to boot and the connection was not already completely up.
I will set a delay in the launch of the app, but it would be much nicer if everstiky could not ask to relogin to evernote each time, but just ask to retry with the same saved credentials. 
Thank you for this nice project

**Comment by itsmejoeeey** [comment]
Glad you enjoy my project.

I've fixed the issue in [new release v0.95.1](https://github.com/itsmejoeeey/eversticky/releases/tag/v0.95.1). Reopen if any problems persist.

**Comment by wokawoka** [comment]
I've just realized that in the meanwhile you pushed out a new release with a fix. Great.
I've just tested it and I confirm that I'm no more experiencing the problem at launch. 
Thank you very much for the time you are investing in this nice project!
