### ISSUE TITLE
Only deb package works, snap package crashes on launch (Ubuntu 20.04)

### ISSUE THREAD

**Issue by MuhammadAbrarx** [itsmejoeeey/eversticky#6]
>> I downloaded the .deb and succesfully ran/logged in & it automatically loaded some notes
wget https://github.com/itsmejoeeey/eversticky/releases/download/v0.95.2/eversticky_0.95.2-1_amd64.deb
sudo apt install ./eversticky_0.95.2-1_amd64.deb

**Comment by itsmejoeeey** [comment]
Without any additional details, this looks like a duplicate of #5. Closing.

**Comment by MuhammadAbrarx** [comment]
possibly yes, i too have an nvidia card on my laptop
