### ISSUE TITLE
On login loads all notes, no option to chose preferred notes

### ISSUE THREAD

**Issue by MuhammadAbrarx** [itsmejoeeey/eversticky#7]
At This Time Of Review, 
>> I downloaded the .deb and succesfully ran/logged in & it automatically loaded some notes

Automatically created sticky notes of it's own choice, no option provided to chose the notes i want shown

**Comment by itsmejoeeey** [comment]
Notes are loaded from the "Sticky Notes" notebook on Evernote (this is created if it didn't exist prior).

I am not looking at allowing users to individually display notes from within a single notebook.

Eventually I would like to allow users to select one or more custom notebooks to display, but this is not in the immediate roadmap.
