### ISSUE TITLE
Can't edit old notes, it reverts back to its old state when automatically/manually synced

### ISSUE THREAD

**Issue by MuhammadAbrarx** [itsmejoeeey/eversticky#8]
>> Old Shown Notes if edited, reverts back to it's old stage when synced

**Comment by itsmejoeeey** [comment]
Please update your bug report with additional detail such as:

- **Version:** The software version, if any.
- **Reproduction steps:** Clearly, mention the steps to reproduce the bug (in this case include the content of the notes before and after editing).
- **Expected result:** How the application should behave on the above-mentioned steps.
- **Actual result:** What is the actual result of running the above steps i.e. the bug behavior.

**Comment by MuhammadAbrarx** [comment]
- **Version**: 0.95.2
- **Reproduction steps**: try to edit a sticky and wait for it to sync or force sync
- **Expected result**: newly changed sticky data should have updated my main evernote account data but instead it doesn't even last on the sticky note itself, it is the least it should have done
- **Actual result**: New data on the sticky just reverts back to old data

**Comment by MuhammadAbrarx** [comment]
looks to me like Crash on network/sync issue #2 has taken a new form on version 0.95.2 [new form 2]
here it doesn't crash, just reverts back to old data

**Comment by itsmejoeeey** [comment]
I have managed to reproduce the issue.

This bug can only be witnessed if the application fails to communicate with Evernote (`www.evernote.com`) servers - such as when in the absence of an internet connection.

**Comment by itsmejoeeey** [comment]
Just pushed a fix. This will no longer be an issue in the next release.

**Comment by MuhammadAbrarx** [comment]
yes working effectively thanks
