### ISSUE TITLE
Newly created notes crashes automatically

### ISSUE THREAD

**Issue by MuhammadAbrarx** [itsmejoeeey/eversticky#9]
>> Newly Created Notes automatically closes & doesn't create a copy of note at my evernote account

**Comment by itsmejoeeey** [comment]
Please update your bug report with additional detail such as:

- **Version:** The software version, if any.
- **Reproduction steps:** Clearly, mention the steps to reproduce the bug (in this case include the content of the newly created notes).
- **Expected result:** How the application should behave on the above-mentioned steps.
- **Actual result:** What is the actual result of running the above steps i.e. the bug behavior.

**Comment by MuhammadAbrarx** [comment]
- **Version**: 0.95.2
- **Reproduction steps**: Create a New note > write something > wait for it to go away
- **Expected result**: the new sticky note should have stuck where i kept it,as i kept it & also a new note should have been created at my evernote main account with the data of the sticky
- **Actual result**: New Sticky with all data just vanishes

**Comment by MuhammadAbrarx** [comment]
looks to me like Crash on network/sync issue #2 has taken a new form on version 0.95.2 [new form 1]

**Comment by itsmejoeeey** [comment]
I have managed to reproduce the issue.

This bug can only be witnessed if the application fails to communicate with Evernote (`www.evernote.com`) servers - such as when in the absence of an internet connection.

**Comment by itsmejoeeey** [comment]
Investigation has found that the newly created notes aren't "crashing", but rather reverting to their "old state" (uncreated) - hence no longer being visible.

This issue has the same cause and symptoms as #8 (also raised by you). Closing as duplicate...
